### PR TITLE
[BD-14] refactor: remove global font-size from the html tag

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**Description:**
The main aim is to remove global scale from the `html { font-size: 62.5%; }` tag. Consequently, all of child nodes have 1rem = 10px instead of base 16px. Because of this, everyone has to add more styles to all paragon components every time we use them because they are all based on rem units.
In addition, all pages were fixed and displayed correctly according to the current paragon style.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ihor-romaniuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by ihor-romaniuk** [comment]
@connorhaugh Please, take a look at this PR. Thanks in advance.

**Comment by arbrandes** [comment]
@ihor-romaniuk, we just finished a round of refactoring to remove most of the unwieldy `vendor/` styles.  If you care to revisit this and resolve the conflicts, it would be a great time.  Thanks, and apologies for the inconvenience!

**Comment by itsjeyd** [comment]
Hi @ihor-romaniuk, thanks again for your contribution! We're closing this PR at this time because it is stale. You may reopen this pull request, or open a new one, when you have time to come back to this work.

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/80&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2022-10-21+08:25&entry.1917517419=2023-03-01+11:04&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
