### PR TITLE
fixed typo in README.rst

### PR DESCRIPTION
**Pull request by girish946**
Signed-off-by: Girish Joshi <girish@opencraft.com>

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @girish946! I've created [OSPR-6261](https://openedx.atlassian.net/browse/OSPR-6261) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@girish946 Thank you for your contribution. Is this ready for our review?

**Comment by girish946** [comment]
@natabene Thanks, Yes it is ready for the review.

**Review by jristau1984 — APPROVED** [review]

**Comment by edx-webhook** [comment]
@girish946 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/29&entry.1484655318=https://github.com/girish946&entry.752974735=2021-12-09+14:28&entry.1917517419=2022-01-18+17:50&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
