### PR TITLE
feat: upgrade mathjax from v2 to v3

### PR DESCRIPTION
**Pull request by navinkarkera**
See https://github.com/openedx/edx-platform/pull/33555 for details.

### CODE REVIEW

**Comment by itsjeyd** [comment]
Hey @navinkarkera, is this PR ready for review?

**Comment by navinkarkera** [comment]
@itsjeyd Yes.

**Comment by itsjeyd** [comment]
@jristau1984 This PR is ready for engineering review by TNL.

**Comment by tecoholic** [comment]
@navinkarkera Kindly add "jira:2U" label to this, if you have access.

cc: @itsjeyd just in case Navin didn't have the access on this repo.

**Comment by openedx-webhooks** [comment]
I've created issue [TNL-11195](https://2u-internal.atlassian.net/browse/TNL-11195) in the private 2U Jira.

**Comment by itsjeyd** [comment]
Hey @jristau1984, do you have any updates about when we can expect TNL to review this PR?

**Comment by jristau1984** [comment]
@itsjeyd, @wittjeff has offered feedback that the impact of this change needs to be handled in a much more conservative way than just upgrading.  Due to that, it has caused this PR to stall.

**Comment by itsjeyd** [comment]
@jristau1984 Thanks for the update.

> ... this change needs to be handled in a much more conservative way than just upgrading.

To understand better, is that work happening via another PR? Or would @navinkarkera be expected to address @wittjeff's concerns in the context of this PR (and if so where can he find the feedback)?

**Comment by navinkarkera** [comment]
> if so where can he find the feedback?

@itsjeyd We have feedback from Jeff in edx-platform PR: https://github.com/openedx/edx-platform/pull/33555

**Comment by itsjeyd** [comment]
@navinkarkera OK I see. I'll keep this PR in the Blocked status, then. Let me know when you're ready to resume the work here.

CC @jristau1984

**Comment by itsjeyd** [comment]
Hey @navinkarkera, do you have any updates on when this PR might get unblocked?

**Comment by itsjeyd** [comment]
@navinkarkera Friendly ping about my comment above.

**Comment by navinkarkera** [comment]
@itsjeyd Apologies for missing your ping. This is blocked on https://github.com/openedx/edx-platform/pull/33555 and we don't have a go ahead from 2U yet. Once course outline MFE project is completed, we might be able to get this across if 2U agrees.

**Comment by itsjeyd** [comment]
@navinkarkera Sounds good, thanks for the update!

**Comment by bradenmacdonald** [comment]
Hey folks, we are planning to deprecate `frontend-app-library-authoring` and roll all related library authoring functionality into frontend-app-course-authoring. I also don't want any mathjax-related code to appear in the MFEs at all. Each individual XBlock that uses MathJax should provide its own MathJax environment. So I believe this PR can be closed.

**Comment by navinkarkera** [comment]
@bradenmacdonald Makes sense, I'll close the PR.

**Comment by openedx-webhooks** [comment]
@navinkarkera Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/352&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2023-10-26+15:41&entry.1917517419=2024-06-10+07:14&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
