### PR TITLE
[BD-14] Replace studio header with the 

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR replaces the custom header implementation with the common `@edx/frontend-component-header-edx` one.

Also, the PR contains lot of "unrelated changes", which are not really unrelated. The base font-size of the frontend-app is wrong, hence the common header would have smaller fonts, incorrect header height, etc. Because of the fix of the font baseline, I had to change **all** the related scss styles where the unit was not in `px` but `rem`. Furthermore, I had to adjust padding, margin and similar classes to adapt to the baseline changes. This means that **all open PR will contain oversized newly added components after merging this PR**. In case other PRs are merged before this PR get merged, this PR **must be updated**

**JIRA tickets**: https://openedx.atlassian.net/browse/TNL-7403

**Dependencies**: 
* frontend-platform - https://github.com/edx/frontend-platform/pull/116
* frontend-component-header-edx - https://github.com/edx/frontend-component-header-edx/pull/102

**Screenshots**: 

**Normal header**
Screenshot 2020-10-09 at 17 17 18
**Detail header**
Screenshot 2020-10-09 at 17 17 01
**Dropdown**
Screenshot 2020-10-09 at 17 20 04

_The screen recording may load slowly, please be patient_
Screen-Recording-2020-10-09-at-1

As mentioned above, this PR fixes several styling issues as well:

**Before**
Screenshot 2020-10-09 at 10 09 38
**After**
Screenshot 2020-10-09 at 10 44 46

**Before**
Screenshot 2020-10-09 at 17 26 14
**After**
Screenshot 2020-10-09 at 17 25 12

**Sandbox URL**: N/A

**Merge deadline**: None

**Testing instructions**:

1. TBD

**Author notes and concerns**:

1. TBD

**Reviewers**
- [ ] @arbrandes 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-5043](https://openedx.atlassian.net/browse/OSPR-5043) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by natabene** [comment]
@marcotuts is this also a Blended ticket?

**Comment by gabor-boros** [comment]
@natabene Yes it is, BD-14

**Comment by kdmccormick** [comment]
_Thanks for your work so far on this. We're pausing development and code review on BD-14 for now to allow more planning and design to be done before work is resumed on Milestone 3. Until then, edX most likely won't be able to review this PR._

**Comment by gabor-boros** [comment]
Closing in favor of https://github.com/openedx/frontend-app-library-authoring/pull/36 as per https://github.com/openedx/frontend-app-library-authoring/pull/36#issuecomment-1077592668

**Comment by openedx-webhooks** [comment]
@gabor-boros Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/18&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2020-10-09+15:09&entry.1917517419=2022-05-11+07:19&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
