### PR TITLE
[BD-14] feat: add empty options list message

### PR DESCRIPTION
**Pull request by ihor-romaniuk**
**Description:**
Implement empty options message for organizations drop-down on the create library page.

### CODE REVIEW

**Comment by ihor-romaniuk** [comment]
@connorhaugh this PR is ready for review. Please, take a look when possible.

**Review by connorhaugh — APPROVED** [review]
This looks good to me, verified that message matches specs and tested locally.

**Comment by ihor-romaniuk** [comment]
@connorhaugh Conflicts have been resolved. It's ready for a merge if you don't have any objections.

**Comment by openedx-webhooks** [comment]
@ihor-romaniuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/56&entry.1484655318=https://github.com/ihor-romaniuk&entry.752974735=2022-08-16+13:20&entry.1917517419=2022-08-31+13:16&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
