### PR TITLE
[BD-14] Library Authoring - Edit Library Title

### PR DESCRIPTION
**Pull request by UvgenGen**
Description:
Library title is editable by clicking on it like in Account MFE

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UvgenGen!


When this pull request is ready, tag your edX technical lead.

**Comment by connorhaugh** [comment]
Looks good you have some lint fixes to do real quick though.

**Comment by UvgenGen** [comment]
> Looks good you have some lint fixes to do real quick though.

@connorhaugh linter fixed)

**Review by brian-smith-tcril — COMMENTED** [review]
Tested this locally, this is definitely a great feature to add!

One thing I noticed in testing is that the user must click (or tab) outside of the text box to fire onBlur and apply the change (pressing enter doesn't work). When I first tried to edit a Content Library name I pressed enter and nothing happened.

I'm not sure if that's unique to this field, or if it's a UX oddity that exists throughout the rest of Open edX as well.

**Comment by UvgenGen** [comment]
@brian-smith-tcril hi! Should we add handler for enter button?

**Comment by brian-smith-tcril** [comment]
It seems on the Account MFE the pattern is slightly different.

This PR is creating what I'd describe as an "editable header" or "editable title," which is not something we have a [Paragon component](https://paragon-openedx.netlify.app/) for.

### The account MFE has 
image
image
and pressing enter performs a save (with visual feedback)
image

and uses some paragon components (https://github.com/openedx/frontend-app-account/blob/e01b595a0c4be60f886587c62203b35b70f50f61/src/account-settings/name-change/NameChange.jsx), but it seems there is still room for improvement re: component reusability

### This PR has
image
image

### Overall thoughts
I'm not sure if any of these UX questions really belong in the scope of this PR. It's definitely worth documenting the flows that we want to have for MFEs and creating reusable components to support those flows, but I'm not sure that should be a blocker for adding this functionality.

Ideally we can determine:
* What short term changes need to happen to get this PR ready to merge so we can have this functionality added quickly?
* What long term changes need to happen to support this flow with better code reuse and UX consistency?

**Comment by arbrandes** [comment]
@brian-smith-tcril, @UvgenGen this MFE is in need of a UX and styling makeover anyway.  We should stick to the minimal changes here: adding the enter key handler, for instance.

Longer term, Brian and I are discussing what to do about bringing the MFE up to speed with Paragon (via https://github.com/openedx/frontend-wg/issues/90).

**Comment by UvgenGen** [comment]
@arbrandes I've added the enter key handler

**Comment by connorhaugh** [comment]
@arbrandes is there anything specific we need to handle here then? 

>  this MFE is in need of a UX and styling makeover anyway. We should stick to the minimal changes here: adding the enter key handler, for instance.

seems to imply that this PR can be approved.

**Comment by arbrandes** [comment]
Yeah, we can totally merge this!

**Comment by openedx-webhooks** [comment]
@UvgenGen 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/61&entry.1484655318=https://github.com/UvgenGen&entry.752974735=2022-08-25+12:33&entry.1917517419=2022-10-17+19:32&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
