### PR TITLE
feat!: remove Transifex calls for OEP-58 | FC-0012

### PR DESCRIPTION
**Pull request by hopewise**
## Breaking change!

This change breaks the Jenkins transifex integration which has been deprecated in favor of the new GitHub Transifex App integration as part of [OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

## Changes

 - Removes all direct use of `tx pull` and `tx push` commands from the micro-frontend in favor
of the [`atlas pull`](https://github.com/openedx/openedx-atlas/) command.
 - Remove source and language translations from the repositories, hence no `.json` files will be committed into the repos. 
 - `src/i18n/index.js` should export and empty array so the `make pull_translations` override it with the dynamic list of languages.
 - Remove the experimental `OPENEDX_ATLAS_PULL` flag to make `atlas pull` the default. 
 - Remove all Transifex related `Makefile` targets and other files.

Test results
------------

 - [ ] Verify that `make pull_translations` works as expected.

<details><summary>make pull_translations test results</summary>

```
# I've run the following commands:
$ make requirements
$ make pull_translations
$ git diff

# Output of the commands:

make pull_translations
rm -rf src/i18n/messages
mkdir src/i18n/messages
cd src/i18n/messages \
      && atlas pull \
               translations/frontend-component-footer/src/i18n/messages:frontend-component-footer \
               translations/paragon/src/i18n/messages:paragon \
               translations/frontend-app-library-authoring/src/i18n/messages:frontend-app-library-authoring
Pulling translation files
 - directory: translations/frontend-component-footer/src/i18n/messages:frontend-component-footer translations/paragon/src/i18n/messages:paragon translations/frontend-app-library-authoring/src/i18n/messages:frontend-app-library-authoring
 - repository: openedx/openedx-translations
 - branch: main
 - filter: Not Specified
 - expand-glob: Not Specified
Creating a temporary Git repository to pull translations into "./translations_TEMP"...
Done.
Setting git sparse-checkout rules...
Done.
Pulling translation files from the repository...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 21 (delta 15), reused 16 (delta 12), pack-reused 0
Receiving objects: 100% (21/21), 19.41 KiB | 320.00 KiB/s, done.
Resolving deltas: 100% (15/15), done.
Your branch is up to date with 'origin/main'.
Done.
Copying translations from "./translations_TEMP/translations/frontend-component-footer/src/i18n/messages" to "./frontend-component-footer"...
Done.
Copying translations from "./translations_TEMP/translations/paragon/src/i18n/messages" to "./paragon"...
Done.
Copying translations from "./translations_TEMP/translations/frontend-app-library-authoring/src/i18n/messages" to "./frontend-app-library-authoring"...
Done.
Removing temporary directory...
Done.

Translations pulled successfully!
./node_modules/.bin/intl-imports.js frontend-component-footer paragon frontend-app-library-authoring

```

</details> 

Merge timeline
-----------------------

This should only be merged after [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) is fully implemented.

The timing announcement will be shared by @brian-smith-tcril on [#translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T) Open edX Slack channel.

Keep this pull request as a draft to prevent accidental merge.

### Pre-merge checklist

 - [ ] Wait for approval on https://github.com/openedx/wg-translations/issues/20

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @hopewise!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by itsjeyd** [comment]
@hopewise Thank you for this contribution! Please let us know when the changes are ready for review.

**Comment by OmarIthawi** [comment]
@itsjeyd this is now ready for review among other Transifex deprecation PRs:

 - https://github.com/openedx/wg-translations/issues/20

We're continuing to create more pull requests like this in a total of ~40 PRs and keep them in draft until we get a greenlight from `@brian-smith-tcril` to merge them at once.

**Comment by itsjeyd** [comment]
Sounds good @OmarIthawi, thank you for the update.

**Comment by jesperhodge** [comment]
I'm doing my best to review this. So I followed the steps in the PR descriptions under "Test Results". I got an error when trying to test locally:
1. I ran `make dev.shell.frontend-app-library-authoring` on my hosted-devstack
2. `make requirements` worked
3. `make pull_translations` gave me an error:
`make pull_translations
rm -rf src/i18n/messages
mkdir src/i18n/messages
cd src/i18n/messages \
      && atlas pull \
               translations/frontend-component-footer/src/i18n/messages:frontend-component-footer \
               translations/paragon/src/i18n/messages:paragon \
               translations/frontend-app-library-authoring/src/i18n/messages:frontend-app-library-authoring
/bin/sh: 2: atlas: not found
make: *** [Makefile:38: pull_translations] Error 127`

**Review by OmarIthawi — APPROVED** [review]
@brian-smith-tcril @itsjeyd this one is ready for merge and approved by 2U

cc: @timmc-edx

**Comment by OmarIthawi** [comment]
> I'm doing my best to review this. So I followed the steps in the PR descriptions under "Test Results". I got an error when trying to test locally:
> 
> 1. I ran `make dev.shell.frontend-app-library-authoring` on my hosted-devstack
> 2. `make requirements` worked
> 3. `make pull_translations` gave me an error:
> 
> ```
> make pull_translations
> rm -rf src/i18n/messages
> mkdir src/i18n/messages
> cd src/i18n/messages \
>       && atlas pull \
>                translations/frontend-component-footer/src/i18n/messages:frontend-component-footer \
>                translations/paragon/src/i18n/messages:paragon \
>                translations/frontend-app-library-authoring/src/i18n/messages:frontend-app-library-authoring
> /bin/sh: 2: atlas: not found
> make: *** [Makefile:38: pull_translations] Error 127
> ```

Sorry for the delayed feedback @jesperhodge 

Please either install `atlas` locally or follow the steps below:

```
npm ci
PATH=$PATH:./node_modules/.bin/ make pull_translations
```

This should use the `./node_modules/bin/atlas` binary, which fixes the issue you've posted

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by OmarIthawi** [comment]
@brian-smith-tcril rebased.

**Comment by openedx-webhooks** [comment]
@hopewise 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-library-authoring&entry.867055334=https://github.com/openedx/frontend-app-library-authoring/pull/351&entry.1484655318=https://github.com/hopewise&entry.752974735=2023-10-21+14:40&entry.1917517419=2024-03-21+18:46&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
